version: '3.5'

services:

  ghost:
    image: jahrik/arm-ghost:aarch64
    ports:
      - 8083:2368
    networks:
      - traefik
    volumes:
      - /mnt/g1/ghost/content:/var/lib/ghost/content
    environment:
      url: 'http://homelab.business'
      database__client: mysql
      database__connection__host: "${DB_HOST}"
      database__connection__user: "${DB_USER}"
      database__connection__password: "${DB_PASS}"
      database__connection__database: "${DATABASE}"
      mail_transport: "SMTP"
      mail_options_service: "${MAIL_SRVC}"
      mail_options_auth_user: "${MAIL_USER}"
      mail_options_auth_pass: "${MAIL_PASS}"
    deploy:
      # replicas: 1
      labels:
        traefik.enable: 1
        traefik.port: 2368
        traefik.backend: ghost
        traefik.docker.network: traefik
        traefik.frontend.rule: Host:homelab.business
        # traefik.backend.loadbalancer.swarm: 1
        # traefik.backend.loadbalancer.method: drr
      placement:
        constraints:
          - node.labels.arch == aarch64

  jahrik:
    image: jahrik/arm-ghost:armv7l
    environment:
      url: 'http://jahrik.me'
    ports:
      - 8085:2368
    networks:
      - traefik
    # volumes:
      # - /mnt/g1/ghost/content:/var/lib/ghost/content
    deploy:
      # replicas: 1
      labels:
        traefik.enable: 1
        traefik.port: 2368
        traefik.backend: jahrik
        traefik.docker.network: traefik
        traefik.frontend.rule: Host:jahrik.me
        # traefik.backend.loadbalancer.swarm: 1
        # traefik.backend.loadbalancer.method: drr
      placement:
        constraints:
          - node.labels.arch == arm32v7

networks:
  traefik:
    name: traefik
    driver: overlay
    external: true
